// <auto-generated />
namespace TokenBasedReception.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class UpdaterelationsinPatientandWaitingQueue : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UpdaterelationsinPatientandWaitingQueue));
        
        string IMigrationMetadata.Id
        {
            get { return "201908112320392_Update relations in Patient and WaitingQueue"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
