// <auto-generated />
namespace TokenBasedReception.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class PatientDiseaseMapping : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PatientDiseaseMapping));
        
        string IMigrationMetadata.Id
        {
            get { return "201908081035091_Patient-Disease-Mapping"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
